name: RUN SCRIPT

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  extract-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install requests

      - name: Gather m3u
        run: |
          cat << 'EOF' > run_scraper.py
          import requests
          import urllib3
          import re

          urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

          def main():
              url = "https://dlhd.pk/24-7-channels.php"
              
              # Emulating a standard desktop browser profile to breeze past the Adscore check
              headers = {
                  "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.
